branch-defaults:
  master:
    environment: english-tutor-platform-dev
    group_suffix: null
environment-defaults:
  english-tutor-platform-dev:
    branch: null
    repository: null
global:
  application_name: english-tutor-platform
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
